language: c
script:
 - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then git clean -x -d -f && ./BUILD all ; fi
compiler: 
 - gcc
 - gcc-4.8

env:
  global:
   - secure: "tARd2A5pHaoxooEXFhjnbLcPCp5cKPZTH4f+tMajMrSAkSmuNpL+GxUsa3wGhTRm0S3LOHtstqB0w8aRkdmwoytj64D9idX6121Ui9NuA47YL+NFRs76Oh3JcEzvdTu2ZhfTlvOwpDR1zjXhBBSVhFB8Tr2+N9Ywz95SjIgybx8V8B6jk946lPMK5dm1MBJ9iKy9Xngv49DNy5A3g7nalzK3+gL8yeKLdgu10KqZkLFXcdxoU2Nq5A/T8mrufxEe7tYmmGRpN9YqXn4rRnKg3BrEPXWcYfD8nkyUeaCRXIx9autWpGFU8HmxvWvOKrcDR6FjzrD7uWSlVGh9WGoomwSCgRb9pJSYOnORGrlTUkO/badEZHXBCAlCV6RgL2CFENxr55p2Ddb+iXxTM+iP5sJ1bhVQVbIL590lNqMkxvhT46g+meE6xIil+05OC5PR2B/SqhQ0jqcvjKRsK232KobseKQ1h7+jm2kZMfl45nPq1q+dlsN1IvKKN5XgyIhAje1eudvAeBzFbl0I7k0ZUnikKGW0AB1pjTDcFLIQFuzTZOix1uYrahI25oo1FgE1iLCbhgXQKtAW++sgxdb31fX7Rzi+YZCBprJ8PbJ4vUiUIhKfb5ORT71cmew7GVlFmKclVgDMaNOeGiJjUsHgPXx0sDsHsGT4RLwvxzpg+Cw="
   - ARCH=amd64
   - HARVEY=$TRAVIS_BUILD_DIR
   - PATH=$PATH:$HARVEY/util

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
  coverity_scan:
    project:
      name: "elbing/harvey"
      description: "Build submitted via Travis CI"
    notification_email: harvey@googlegroups.com
    build_command_prepend: "./BUILD utils"
    build_command:   "./BUILD all"
    branch_pattern: coverity_scan

