name: harvey

on:
  push:
    branches: [ master ]
    tags: 
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        cc:
          - gcc-9
#          - clang
#          - clang-9
          - clang-10
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo add-apt-repository ppa:gophers/archive -y
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main' -y
        sudo apt-get update
        sudo apt-get install -y --force-yes ${{ matrix.cc }} rc golang-1.11-go
    - name: build
      env:
        ARCH: amd64
        CC: ${{ matrix.cc }}
      run: ./util/ci.sh
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
    - name: upload harvey 32bit
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./sys/src/9/amd64/harvey.32bit
        asset_name: harvey.32bit
        asset_content_type: application/octet-stream
    - name: upload harvey
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./sys/src/9/amd64/harvey
        asset_name: harvey
        asset_content_type: application/octet-stream
